Refit3355/refit_backend

src/main/java/com/refit/app/domain/auth/controller/MemberController.java, src/main/java/com/refit/app/domain/auth/dto/response/BasicInfoResponse.java, src/main/java/com/refit/app/domain/auth/mapper/MemberMapper.java, src/main/java/com/refit/app/domain/auth/service/MemberService.java, src/main/java/com/refit/app/domain/auth/service/MemberServiceImpl.java, src/main/resources/mapper/auth/MemberMapper.xml
#33 
- 마이페이지에서 내 기본 정보 수정을 위해 필요한 정보 조회 API를 구현했습니다.
=> [FEAT] 내 기본 정보 조회 API 구현

src/main/java/com/refit/app/domain/auth/dto/response/KakaoVerifyResponse.java, src/main/java/com/refit/app/domain/auth/service/KakaoOAuthServiceImpl.java
#43 
- 카카오 API 응답에 건강 데이터를 추가했습니다. (HAIR_CONCERN, SKIN_CONCERN, HEALTH_CONCERN)
=> [FEAT] 카카오 API 응답에 건강데이터 추가 (#43)

src/main/java/com/refit/app/global/config/SwaggerConfig.java
=> [FEAT] 스웨거 운영환경/로컬환경 설정 추가

Jenkinsfile, src/main/java/com/refit/app/global/config/SwaggerConfig.java
=> [DEPLOY] 8월 25일 배포 #2

Jenkinsfile
=> [FIX] OCI-WALLET 누락 부분 수정

Jenkinsfile, src/main/java/com/refit/app/global/config/SwaggerConfig.java
=> [DEPLOY] 8월 25일 배포 #3

src/main/java/com/refit/app/domain/combination/controller/CombinationController.java, src/main/java/com/refit/app/domain/combination/dto/CombinationResponseDto.java, src/main/java/com/refit/app/domain/combination/dto/response/CombinationListResponse.java, src/main/java/com/refit/app/domain/combination/dto/response/MyCombinationResponse.java, src/main/java/com/refit/app/domain/combination/mapper/CombinationMapper.java, src/main/java/com/refit/app/domain/combination/service/CombinationService.java, src/main/java/com/refit/app/domain/combination/service/CombinationServiceImpl.java, src/main/resources/mapper/combination/CombinationMapper.xml
#56 
- 타입(전체,뷰티,헬스), 정렬(최신,인기,저가,고가)에 따른 조회 구현
=> [FEAT] 커서 기반 조합 조회 API

src/main/resources/mapper/me/MeMappper.xml
#62 
- Order Status 변경사항 반영 (결제전,만료 아이템은 보이지 않게 처리)
=> [REFACTOR] Order Status 변경사항 반영

src/main/java/com/refit/app/domain/chat/dto/response/ChatMessageResponse.java, src/main/java/com/refit/app/domain/chat/service/ChatServiceImpl.java, src/main/java/com/refit/app/domain/product/mapper/ProductMapper.java, src/main/java/com/refit/app/global/config/SecurityConfig.java, src/main/resources/mapper/chat/ChatMapper.xml, src/main/resources/mapper/product/ProductMapper.xml
- #64 
채팅 응답 반환시 상품 아이디가 있는 경우, 상품 테이블 조인 후 반환하도록 수정
=> [REFACTOR] 채팅 응답 수정

src/main/java/com/refit/app/domain/chat/dto/response/ChatListResponse.java, src/main/java/com/refit/app/domain/chat/mapper/ChatMapper.java, src/main/java/com/refit/app/domain/chat/service/ChatServiceImpl.java, src/main/resources/mapper/chat/ChatMapper.xml
=> [REFACTOR] 채팅 기록 조회 응답 수정

src/main/java/com/refit/app/domain/auth/dto/MemberRowDto.java, src/main/java/com/refit/app/domain/auth/dto/response/LoginResponse.java, src/main/java/com/refit/app/domain/auth/service/KakaoOAuthServiceImpl.java, src/main/java/com/refit/app/domain/auth/service/MemberServiceImpl.java, src/main/resources/mapper/auth/MemberMapper.xml
#69 
- 카카오 / 일반 로그인 시, 응답에 프로필 사진 url을 추가했습니다.
=> [FEAT] 카카오/일반 로그인시 응답에 프로필 url 추가 (#69)

src/main/java/com/refit/app/domain/combination/service/CombinationServiceImpl.java, src/main/java/com/refit/app/domain/me/service/MeServiceImpl.java, src/main/java/com/refit/app/domain/product/service/ProductServiceImpl.java
#79 
할인가 100원 단위 절삭값 반영되도록 업데이트
=> [REFACTOR] 할인가 100원 단위 절삭 반영

src/main/java/com/refit/app/domain/product/service/ProductServiceImpl.java, src/main/java/com/refit/app/infra/cache/RedisRecommendationCacheRepository.java
=> [REFACTOR] 캐싱 오류를 잡기위한 임시 수정

src/main/java/com/refit/app/infra/cache/RedisRecommendationCacheRepository.java
=> [FIX] 오타 수정

build.gradle, src/main/java/com/refit/app/domain/analysis/ai/OpenAiNarrative.java, src/main/java/com/refit/app/domain/analysis/ai/OpenAiVisionOcr.java, src/main/java/com/refit/app/domain/analysis/service/AnalysisServiceImpl.java, src/main/java/com/refit/app/infra/image/ImagePreprocessor.java
#86 
- 성분 분석 API 응답 속도 개선
- 이미지 다운스케일 및 압축 코드 추가
=> [FEAT] 성분 분석 이미지 다운스케일 및 압축 코드 작성 (#86)

build.gradle, src/main/java/com/refit/app/domain/analysis/ai/OpenAiNarrative.java, src/main/java/com/refit/app/domain/analysis/ai/OpenAiVisionOcr.java, src/main/java/com/refit/app/domain/analysis/dto/AnalysisStatus.java, src/main/java/com/refit/app/domain/analysis/dto/response/AnalysisResponseDto.java, src/main/java/com/refit/app/domain/analysis/service/AnalysisServiceImpl.java, src/main/java/com/refit/app/infra/image/ImagePreprocessor.java
#90 
- 이미지 성분 분석 예외처리 (영양제 or 화장품 사진이 아닐 경우)
- 이미지 처리 코드 개선 (속도 향상을 위해)
=> [FEAT] 이미지 성분 분석 예외 처리 및 이미지 처리 코드 개선

Jenkinsfile
=> [FIX] 젠킨스파일 수정

Jenkinsfile, src/main/resources/application.properties
=> [FIX] properties 충돌문제로 수정

Jenkinsfile, src/main/resources/application.properties
=> [DEPLOY] 9월 3일 1배포 #2

src/main/java/com/refit/app/domain/notification/mapper/DeviceMapper.java, src/main/java/com/refit/app/domain/notification/service/DeviceServiceImpl.java, src/main/java/com/refit/app/domain/order/dto/OrderItemDto.java, src/main/resources/mapper/notification/DeviceMapper.xml, src/main/resources/mapper/order/OrderMapper.xml
=> [FIX] 마이핏 & FCM토큰 수정

src/main/java/com/refit/app/domain/payment/dto/OrderItemRowDto.java, src/main/java/com/refit/app/domain/payment/dto/response/ConfirmPaymentItemDto.java, src/main/java/com/refit/app/domain/payment/dto/response/ConfirmPaymentResponse.java, src/main/java/com/refit/app/domain/payment/service/PaymentServiceImpl.java, src/main/resources/mapper/payment/PaymentMapper.xml
- close #107
- 결제완료 페이지용 주문상세내역 응답값 추가
=> [REFACTOR] 결제완료 응답 - 주문 상세내역 추가 (#107)

src/main/java/com/refit/app/domain/me/dto/MyOrderDto.java, src/main/java/com/refit/app/domain/me/dto/MyOrderItemDto.java, src/main/java/com/refit/app/domain/me/service/MeServiceImpl.java, src/main/resources/mapper/me/MeMappper.xml
- close #109
- 환불금액 미리보기 관련 응답값 추가
=> [REFACTOR] 주문내역 조회 응답값 추가 (#109)

src/main/java/com/refit/app/domain/product/service/ProductServiceImpl.java
=> [REFACTOR] 추천 상품 셔플 로직 추가

src/main/java/com/refit/app/domain/product/controller/ProductController.java, src/main/java/com/refit/app/domain/product/dto/request/AiRecommendRequest.java, src/main/java/com/refit/app/domain/product/service/ProductService.java, src/main/java/com/refit/app/domain/product/service/ProductServiceImpl.java, src/main/java/com/refit/app/infra/cache/RecommendationCacheKey.java
=> [REFACTOR] 추천 상품 캐싱키 업데이트

src/main/java/com/refit/app/domain/product/controller/ProductController.java, src/main/java/com/refit/app/domain/product/dto/request/AiRecommendRequest.java, src/main/java/com/refit/app/domain/product/service/ProductService.java, src/main/java/com/refit/app/domain/product/service/ProductServiceImpl.java, src/main/java/com/refit/app/infra/cache/RecommendationCacheKey.java
=> [DEPLOY] 9월 7일 배포 #2

src/main/java/com/refit/app/domain/analysis/ai/OpenAiNarrative.java, src/main/java/com/refit/app/domain/analysis/dto/response/AnalysisResponseDto.java, src/main/java/com/refit/app/domain/analysis/policy/ScoringPolicy.java, src/main/java/com/refit/app/domain/analysis/service/AnalysisServiceImpl.java, src/main/java/com/refit/app/global/config/OcrWebClientConfig.java, src/main/java/com/refit/app/infra/image/ImagePreprocessor.java, src/main/java/com/refit/app/infra/ocr/ClovaOcrProps.java, src/main/java/com/refit/app/infra/ocr/ClovaOcrProvider.java, src/main/java/com/refit/app/infra/ocr/OcrProvider.java
#105 
- 기존 OPENAI API를 통한 전 성분 텍스트 추출 로직을 NAVER CLOVA OCR API로 변경해 속도 개선
- 매칭률 가중치 개선 (노션에 정리 예정)
=> [FEAT] 성분 분석 API 속도 개선

src/main/java/com/refit/app/domain/payment/dto/VaIssuedUpdateParam.java, src/main/java/com/refit/app/domain/payment/dto/request/ConfirmPaymentRequest.java, src/main/java/com/refit/app/domain/payment/dto/request/PartialCancelRequest.java, src/main/java/com/refit/app/domain/payment/dto/response/ConfirmPaymentResponse.java, src/main/java/com/refit/app/domain/payment/mapper/PaymentMapper.java, src/main/java/com/refit/app/domain/payment/service/PaymentCancelLogService.java, src/main/java/com/refit/app/domain/payment/service/PaymentCancelLogServiceImpl.java, src/main/java/com/refit/app/domain/payment/service/PaymentServiceImpl.java, src/main/java/com/refit/app/domain/payment/service/PaymentWebhookServiceImpl.java, src/main/java/com/refit/app/global/config/SecurityConfig.java, src/main/resources/mapper/payment/PaymentMapper.xml
- close #100
- 가상계좌/계좌이체 환불 시 DB에 저장된 VA 계좌정보를 활용하도록 수정 
- `confirm`, `partialCancel` 메서드 리팩토링
=> [REFACTOR] 가상계좌 결제방식 환불처리 개선 및 결제 관련 리팩토링

Jenkinsfile
=> [DEPLOY] Jenkins 파일 업데이트

src/main/resources/mapper/combination/CombinationMapper.xml
=> [FIX] 조합왕 검색시 가격 버그 수정
